### ISSUE TITLE
TLS and macaroon file storage locations

### ISSUE THREAD

**Issue by robertclarkson** [boltcard/boltcard#3]
Service file assumes these are stored in the boltcard root dir, so might be good to write in the instructions that these should be moved there. 

Real minor point but In the service file it uses the boltcard folder path a few times so might be good if possible to set this as a constant at the top and reuse further down and then the user can just change this path.

**Comment by PeterRounce** [comment]
I thought this was covered in the line:
-  "edit `boltcard.service` in the section named `boltcard service settings` "

Each line in the service config needs to be reviewed and changed as needed.
The file has examples only.

For the TLS cert and macaroon, the paths would be different for a different login.
They could also be stored somewhere else.

Re: folder path
The TLS cert and macaroon may be elsewhere which would only leave the launch script.
Planning to leave as is for now.
