### ISSUE TITLE
How do i find what card values to set in "add_card_data.sql"

### ISSUE THREAD

**Issue by robertclarkson** [boltcard/boltcard#4]
Might be good to explain how to find / create these values. 

Is this something my app should do?

**Comment by PeterRounce** [comment]
I have added a section to the FAQ about creating the key value.
https://github.com/boltcard/boltcard/commit/0710557552eb0f897b0e3e7241e97b53c6051b6c

I've added descriptive comments to the SQL fields.
https://github.com/boltcard/boltcard/commit/7e75bc6f810d3cddca3c354da646cc37acc95ddc

Not something for the app currently.
