### ISSUE TITLE
Database creation - Set up Postgres connection details

### ISSUE THREAD

**Issue by robertclarkson** [boltcard/boltcard#5]
If I haven't set Postgres role for my user i get the following error
```
$ ./s_create_db
[sudo] password for <<user>>: 
psql: error: FATAL:  role "<<user>>" does not exist
psql: error: FATAL:  role "<<user>>" does not exist
```

**Comment by robertclarkson** [comment]
Ah sorry can see that the null value for the lock key is because i have zeros for the lock_key.

I think we need a postgres command to create the cardapp user in that sql script

**Comment by robertclarkson** [comment]
There is no lock_key specified in the add_card_data.sql so this add card SQL fails

**Comment by PeterRounce** [comment]
> There is no lock_key specified in the add_card_data.sql so this add card SQL fails

This is fixed in https://github.com/boltcard/boltcard/commit/7e75bc6f810d3cddca3c354da646cc37acc95ddc

**Comment by PeterRounce** [comment]
updates to address the issues mentioned here with `create_db.sql`

https://github.com/boltcard/boltcard/commit/5f69135c5444cb0933d3dd97203e3b05c3f2e347
https://github.com/boltcard/boltcard/commit/54dbfcb7a398941aeed406681f1b34ce24057bc7
https://github.com/boltcard/boltcard/commit/87ba20df87828b80c807058517b1fced7076697e

**Comment by PeterRounce** [comment]
permission issue fixed in https://github.com/boltcard/boltcard/commit/1d3a858b07484c0c77c1612e8d579befecee1e6b
