### ISSUE TITLE
Do daily limit and per tx limit when doing hub payments.

### ISSUE THREAD

**Issue by robertclarkson** [boltcard/boltcard#51]
The hub does not seem to currently respect the tx and daily limits. Think I remember this being by design, if not too much trouble I think we add those limit checks back in when doing a hub payment

**Comment by chloehjung15** [comment]
#52 
I've created a pull request for this. 
@PeterRounce Do we need to call `Update_payment_paid` function as well?

**Comment by PeterRounce** [comment]
This was left out as card accounting is done in lndhub and it was considered sub-optimal design to have accounting here as well. Consider the case where a payment fails - how is that tracked - is it tracked - how does the user know - etc..

That aside - if we want to do it here it will need to be the same for LndHub as for LND, so should probably be in the `Callback` function to reduce duplicate code.

It needs to include the `Update_payment_paid` function also - in fact it should have this anyhow to prevent the same k1 code being used more than once.

**Comment by robertclarkson** [comment]
I think lets remove the daily limit setting from the app for the moment and just implement the per-tx limit.

**Comment by PeterRounce** [comment]
> I think lets remove the daily limit setting from the app for the moment and just implement the per-tx limit.

Agreed - daily limit is not a great feature even when it's working as it's not obvious to the user what's happening.

https://github.com/boltcard/boltcard-wallet/commit/ce125e24c4840af0861fa53658895cfe5ac613f7
