### ISSUE TITLE
Enable PIN code function

### ISSUE THREAD

**Issue by robertclarkson** [boltcard/boltcard#58]
As per draft LUD
https://github.com/bitcoin-ring/luds/blob/withdraw-pin/xx.md
https://github.com/lnurl/luds/pull/200/files#diff-b03763e9ce2c6b65c01f6808159d6fea9a31cfdda3482bd71dee60cf117a4a5a

**Comment by PeterRounce** [comment]
related branches
https://github.com/boltcard/boltcard-wallet/tree/card-pin-number
https://github.com/boltcard/boltcard-lndhub/tree/card-pin-number

related issues
https://github.com/boltcard/bolt-nfc-android-app/issues/32
https://github.com/boltcard/bolt-card-pos/issues/15

**Comment by PeterRounce** [comment]
https://github.com/boltcard/boltcard/tree/card-pin-number

card table database fields

- pin_enable
- pin_number
- pin_limit_sats

added for

- createboltcard
- updateboltcard

internal api calls

TODO:
callback interactions as in
https://github.com/bitcoin-ring/luds/blob/withdraw-pin/xx.md

**Comment by PeterRounce** [comment]
3d9e742dc1137ac12a8fe08b90898b91cb87ae62
lnurlw response includes pinLimit when configured in the card record

**Comment by PeterRounce** [comment]
Database records for PIN can be set with the internal API [done]

LNURLw includes the pinLimit when the card record is set (pin_enable, pin_number, pin_limit_sats) [done]

PIN number check on LNURLw callback [to do]

**Comment by arcbtc** [comment]
I don't understand what this pin is solving? 
PoS can still ie "I will only take x, honest, now give me the pin"
Its still possible to get the pin if the card is stolen. 
It all seems pointless

**Comment by PeterRounce** [comment]
> I don't understand what this pin is solving? 
> PoS can still ie "I will only take x, honest, now give me the pin"
> Its still possible to get the pin if the card is stolen. 
> It all seems pointless

I think this discussion should be in:

https://github.com/bitcoin-ring/luds/blob/withdraw-pin/xx.md
or 
https://t.me/lnurl/34810

**Comment by PeterRounce** [comment]
Thanks for your comment - this issue is really only for part of the implementation.

There is some discussion on the LUD here that you might find useful.

https://t.me/bolt_card/4154

Feel free to come to the group and discuss it some more 👍

**Comment by PeterRounce** [comment]
> I don't understand what this pin is solving? 
> PoS can still ie "I will only take x, honest, now give me the pin"
> Its still possible to get the pin if the card is stolen. 
> It all seems pointless

Thanks for your comment - this issue is really only for part of the implementation.

There is some discussion on the LUD here that you might find useful.

https://t.me/bolt_card/4154

Feel free to come to the group and discuss it some more 👍

**Comment by robertclarkson** [comment]
> I don't understand what this pin is solving? PoS can still ie "I will only take x, honest, now give me the pin" Its still possible to get the pin if the card is stolen. It all seems pointless
@arcbtc 
The pin solves for when the card is misplaced by the user and someone else picks it up, not a mitigation for a dishonest merchant.
The pin is not stored on the card so unsure how it can be stolen.
This feature was requested by the biggest bolt card user in Brazil he sets up hundreds / thousands of bolt cards for kids to pay for fruit at their school..

**Comment by PeterRounce** [comment]
PIN number check on LNURLw callback [done]
