### ISSUE TITLE
updateboltcardwithpin: could not determine data type of parameter $6

### ISSUE THREAD

**Issue by chloehjung15** [boltcard/boltcard#65]
We're getting this error when trying to update boltcard without PIN.

{"level":"warning","msg":"pq: could not determine data type of parameter $6","time":"2023-08-03T23:41:55Z"}

https://github.com/boltcard/boltcard/blob/797e4db605e3cbcc8e10c7b973724a0cb329208f/db/db.go#L1052

I think you forgot to change `$7` to `$6`.

**Comment by PeterRounce** [comment]
yes - doing this by review only..

thanks for raising this, it should be fixed with https://github.com/boltcard/boltcard/commit/056a52e1ba95ddd44f575d6f40d21691aae33561

**Comment by chloehjung15** [comment]
@PeterRounce 
Yep it's working now thank you
