### ISSUE TITLE
Documentation Bug: Incorrect SDM offsets

### ISSUE THREAD

**Issue by NicolasDorier** [boltcard/boltcard#67]
In [your documentation](https://github.com/boltcard/boltcard/blob/main/docs/CARD_MANUAL.md) you mention.

```
* click after p= and note the p_position (41 in this case)
* click after c= and note the c_position (76 in this case)
```
However, your screenshot shows 73 and 38. Why is it different?

![image](https://github.com/boltcard/boltcard/assets/3020646/10a93fbc-5689-40c7-8651-e56c6d19b765)

**Comment by PeterRounce** [comment]
It's in a different part of the documentation. The screenshot will likely have been for a different URI because I don't own yourdomain.com .

That said, it's possibly a distraction with no value so I'll look to update it.

**Comment by PeterRounce** [comment]
I updated the example so that the numbers match.

**Comment by NicolasDorier** [comment]
@PeterRounce the numbers doesn't match the actual offset of p= and c= of `lnurlw://card.yourdomain.com/ln?p=00000000000000000000000000000000&c=0000000000000000`. I have 31 and 66.

**Comment by PeterRounce** [comment]
@NicolasDorier 

The numbers for p= and c= are the byte offset in the (NDEF File) data (not the character position in the string).

There is some prefix data for the (NDEF File) data before the text `lnurlw://` which I think accounts for the difference between your 31 and 66 values and the values in the document.

![rdh-mod](https://github.com/boltcard/boltcard/assets/99006127/52f0acce-ef2b-4119-b253-5d1e19897772)

I have checked again by going through the instructions with the NXP TagXplorer software and added a further screenshot to the document to clarify.
