### ISSUE TITLE
Error is thrown when inserting Card UID as uppercase. The android app creates an uppercase UID.

### ISSUE THREAD

**Issue by orfeas0** [boltcard/boltcard#8]
UID created in the android app should fill the UID acceptance criteria (in the server/db).

Either create a lowercase UID, or accept uppercase in the backend.

**Comment by PeterRounce** [comment]
The app now generates a lower case UID.
https://github.com/boltcard/bolt-nfc-android-app/commit/24b12f020de050db5a41261005fc8d8269c8cc9e
