### ISSUE TITLE
Multiple approaches to avoid boltcards becoming unusable with a set or reset

### ISSUE THREAD

**Issue by johnheenan** [boltcard/boltcard#80]
Please see https://github.com/NicolasDorier/boltcards-plugin/issues/6#issuecomment-2169168657 for an example of a buggy and messy implementation issue that at least can be partially blamed on document on this github at https://github.com/boltcard/boltcard/blob/main/docs/DETERMINISTIC.md

**Comment by NicolasDorier** [comment]
I am the author of both. It isn't a problem in the specification.

The problem is that if the server is on a new version, while the card is on the old one, then the server is unable to check the card.
Skipping the check, while fixing your situation, mean that anybody can get the 5 keys so long as they know the UID, which isn't acceptable.

**Comment by NicolasDorier** [comment]
It may be possible to both brute force and checking non-replay by remembering old version's counter. Will check

**Comment by johnheenan** [comment]
I am in no way advocating any weakening of card security. My point has not been understood. I will try and explain it better.

**I believe there should be four recordable card states and they should form part of the specification:**

1. Confirmed set
2. Confirmed reset
3. Unconfirmed set
4. Unconfirmed reset

When an action is undertaken that a server believes has altered keys on the card itself (either from keys set to keys reset on the card itself or from keys reset to keys set on the card itself) AND this has not been confirmed BY the server as having occurred on the card itself THEN the server should record there is an unconfirmed state change on the card and should keep appropriate records of what the previous state was and the desired state is.

How this is implemented is immaterial. To help implementers, I believe the bolt card specification should recognise the existence of such additional card states in addition to the rather obvious ones of set and reset.

In an implementation, if an attempt is made to use a card whose state has not been successfully changed then an appropriate message can be passed and remedial action can be taken if appropriate and the user has the authority to take such action.

This is robust and is better than leaving a card in an unrecoverable state through not keeping records sufficient to attempt another state change, if the previous state change was not successful.

The following points are irrelevant to my main point because what I am advocating is a change to the specification but these help with context

I currently have five unusable cards.

Since making my points I have examined source code in BTCPay Server in detail.

1. I note the bolt card database records do not even record a specific card state of set or not, as mentioned in the document. Interpreting a card state relies on the presence or absence of data in a field.

2. I also noted that payment ID is also used as part of the key (which is contrary to the specification but is more robust). You have also pointed out use of payment ID in reply https://github.com/NicolasDorier/boltcards-plugin/issues/6#issuecomment-2209637442

From my code examination I see that there are two different code paths for bolt card set and reset:

1.  A more robust code path that uses undocumented features of the BTCPay vault app, can be used with a generic USB NFC card reader and waits to see that the card was actually set or reset. I assume was used for code development and testing.

2. A code path that on attempted set or reset of a bolt card with a mobile phone, may or may not successfully set or reset the card. For a card reset from a previous set state there is no change to boltcard database record for the card to indicate a card was reset. This is not necessarily a problem under normal use. It is just data that can be interpreted in a subsequent code action as long as it is recognised the original card may now be in a reset state. But it is far from obvious, is highly confusing and is vulnerable to a card not having had its state successfully altered.

In general, the code strikes me as robust and so easily fixable.

I don't want to go into more depth. I don't think there is much point given I have issues with the specification itself.

**Comment by NicolasDorier** [comment]
@johnheenan I believe there is a way avoid bricking cards without having to record those 4 states (and the potential headaches, if the actual card isn't really in the state expected by the server)

When a reset is done, I believe the server can detect if the card is using an old version, and return the correct keys.

However, note that it is always possible to brick cards if those move while being flashed. Knowing the underlying NTag424 protocol, I don't there is robust way to prevent this. But at least I may be able to make it a bit more robust without changing the protocol.

**Comment by johnheenan** [comment]
I am currently addressing this issue at https://github.com/NicolasDorier/boltcards-plugin/issues/6#issuecomment-2211601657.

My comment has proposed a solution to bricking cards that while not an explicit recognition of four card states, is so in practice.

If such a solution is accepted then I believe there should be an explicit change to the specifications.

It should be mentioned that there is a change to the deterministic specifications that has not been included in the specifications yet (using an additional id for part of the key generation). While this complicates the proposed solution, it would not alter an approach of implicitly using four card states.

**Comment by NicolasDorier** [comment]
@johnheenan can you ping me directly on chat.btcpayserver.org or via twitter so we talk about the proposal

**Comment by johnheenan** [comment]
@NicolasDorier chat.btcpayserver.org is hung (nneds a reboot?) and I don't have an establshed twitter account I chat on. Maybe I should make the plunge to becoming a citizen of twitter of, despite its near uselss signal to noise ratio.

I have specific, non trivial, reasons why boltcards need to be protected from becoming bricked, despite their very low cost. If cards are easily bricked then this affects trust and image, and has real consequences for some communities which cannot be easily explained to those of us with high high levels of privilige.

**Comment by johnheenan** [comment]
@NicolasDorier I am currently connected to chat.btcpayserver.org with same user name as here: @johnheenan

I don't know what your user name is on chat.btcpayserver.org. If it is @NicolasDorier then it is not visible.

**Comment by PeterRounce** [comment]
I would like to add a few observations to this issue.

- While it is difficult to measure the percentage, people do brick their cards occasionally.
- This happens for a variety of reasons, often during experimentation with different services.
- User programming when not holding the card to the programming device long enough is common. It takes much longer than a payment read.
- Losing the keys is also common when self programming and experimenting.
- Most programming is done with https://github.com/boltcard/bolt-nfc-android-app which uses the NXP TapLinx library. Programming progresses the card through many states to finally achieve a card state with keys and security permissions needed. There may be opportunities to harden the device to card link, control the protocol and card state with more low level detail. It's a significant undertaking. Nobody who has done this so far has open sourced it. It could be fun too, if you have time & motivation.
- It's not reasonable to hold @NicolasDorier solely responsible for this type of issue, it's non-trivial and we can all probably improve it.
- You mention "specific, non-trivial reasons" for non bricking. This is solvable. Don't have the end-user program the card. Nicholas, Motolese, Swiss Bitcoin Pay and others have programmed hundreds (maybe thousands) of cards in batches with very high success rates (>95%) giving fully tested working cards which are then are unbrickable without physically destroying the card.

All this said - thank you for bringing up the issue on GH so we can record and track it.
I look forward to seeing any improvements we can achieve.

**Comment by johnheenan** [comment]
Thanks to @PeterRounce for input.

The most important point is acknowledging the problem.

I partly blamed the boltcard specifications for the issue.  @NicolasDorier told us he wrote the specs. That does not alter any attributable blame (which is not to Nicolas, it is to the standard). Nicolas has every right to deflect blame upwards if he wishes, which he has not. The 'specifications' are more a 'standard' than a specification. A 'standard' usually emanates through a really complex and recognised process with formal recognition by recognised industry standards bodies whose members vote. There is no indication of any of this. Nicolas deserves huge credit for what he has achieved with the specifications and BTCPay server. My feeling is that Nicolas has helped move an industry from 'impractical' to 'almost practical'. The multiple mobile phone app authors (including @robertclarkson, @chloehjung and @PeterRounce) deserve credit also. I have inspected the source code of the mobile app. It is well done, elegant and does an excellent job with far from ideal conditions. 

However for sheer amount of work, most of the credit must go to Nicholas.

By the way I would not call a success rate of 95% for programming card acceptable if the 5% faulty cards end up in the hands of customers. With improved specifications, faulty cards can be recovered into usable cards. Faulty cards are so unnecessary and fixable. I am sure more experienced handlers could easily get the fault rate, requiring recovery action, down to well under 1%.

**Comment by johnheenan** [comment]
I should specifically add I had few problems with programming blank NTAG NXP 424 NFC cards as boltcards, which I assume is what is being claimed for the 95% quoted success rate.

However, we are going from users expecting to have cards pre programmed (as from a bank) to users expecting to be able to program and reset cards themselves (boltcards and BTCPay Server)

**Where I have has an eventual near 100% failure rate is with reusing cards (reset and set again).** This concept will appear strange to those of us who are told, with dire warnings, to cut credit and debit cards in half when a new one is received. Banks never instruct us to reset and reprogram our cards. While it might seem silly to mention this, this is what BTCPay Server is offering us with boltcards.

With BTCPAy server we have being explicitly introduced to the concept of 'reset' and 'set' for boltcards by users themselves. Therefore we expect it to work for users without having to explain ourselves or apologise for it. Currently the boltcards specifications are not robust enough for this. This is the reason for my proposal of a recognition of four card states and temporary recording of successive change data until confirmation of change (to enable replay of 'reset' and 'set' in case of faulty programming).

Recording of successive change enables a data set for derivation of current keys of the boltcard to be found by reading the boltcard. Hence the boltcard can then be successfully reset and set again, even if a previous attempt failed.

**Comment by johnheenan** [comment]
New relevant issue at [Fault in key change algorithm leading to bricked cards](https://github.com/boltcard/bolt-nfc-android-app/issues/42)

Have made specific suggestions to stop boltcards becoming bricked. If accepted and works then my previous suggestions re states and recording key change attempt details, while still valid, may not be as big an issue.

**Comment by PeterRounce** [comment]
### Specifications
Imho, the current best set of specifications relating to the current state of bolt card technology is here:
https://github.com/boltcard/boltcard/blob/main/docs/TECHNOLOGY.md

As you will see, @NicolasDorier has contributed two optional specifications:

- [Deterministic Keys (DRAFT FOR COMMENT)](https://github.com/boltcard/boltcard/blob/main/docs/DETERMINISTIC.md)
- [Boltcard Setup via Deeplink](https://github.com/boltcard/boltcard/blob/main/docs/DEEPLINK.md)

My understanding is that these were developed to enable an initiative involving [programming of >2000 cards for Bitcoin Atlantis](https://blog.btcpayserver.org/case-study-bitcoin-atlantis/) .

### Bricked cards
When you get into a flow, with good hardware, you will not really get any bricked cards.
The last stage in the programming process is a test, so customers should never get bricked cards.
The main frustration I have observed is where people have 'special' cards which get bricked.
The process is not perfect, and [your contribution](https://github.com/boltcard/bolt-nfc-android-app/issues/42) is most welcome. I see @robertclarkson has picked up on it also.

**Comment by johnheenan** [comment]
There is an alternative way to program boltcards that is a lot better for high volume use but it as not mentioned in documentation. I stumbled across it by accident when examining BTCPay server source code. It uses BTCPay vault, https://blog.btcpayserver.org/btcpay-vault/, and works with standard cheap USB NFC card readers. It is very fast and reliable. It only requires one hand to program a card and cards do not need to be held, the cards can be briefly laid on a tray or held against the tray.

I am stating this because these are the sort of factors that would encourage medium size and up enterprises.

With regard to programming a lot of boltcards, a mobile app is definitely not the way to go for numerous reasons and would turn enterprises off. For individual and low card volume use, a mobile app like the bolt-nfc-creator app is highly practical and is also great for both proving use cases and promotion purposes, which is very important, such as for YouTube demonstrations. Making it work more reliably, which is realistic, is important.

The sort of issues that are important to encourage enterprise use is rock solid stability, reliability and proven performance.

**Comment by johnheenan** [comment]
> There is an alternative way to program boltcards that is a lot better for high volume use but it as not mentioned in documentation. I stumbled across it by accident when examining BTCPay server source code. It uses BTCPay vault, https://blog.btcpayserver.org/btcpay-vault/,

Clarification:

1. The boltcard factory plugin of BTCPay Server require use of the bolt-nfc-creator-app. It allows very rapid programming of multiple boltcards by creating a new pull payments on BTCPay Server of the same amount, currency and conditions for each boltcard created with the app.

2. The BTCPay Vault interface to a USB NFC card reader only allows interfacing to a single existing pull payment. It is not suitable for rapid creation of new boltcards.

The bolt-nfc-creator-app requires two hands to be used and for the card to be held to the phone. A USB NFC card reader requires only one hand to be used and does not necessarily require the card to be held (the card can be placed on a tray). It also requires use of a PC.

It would be nice if someone or some organisation asked @nicolasdorier if he would be willing to consider being sponsored to port his vault code to software that works the same way as bolt-nfc-creator-app, separate from BTCPay Server. 

With regard to current issues, I have added a detailed comment on potential solution issues at https://github.com/boltcard/bolt-nfc-android-app/issues/42#issuecomment-2241411004 which I hope clarifies that solutions are realistic at the app level.

**Comment by johnheenan** [comment]
I am aware the bolt-nfc-creator app is a React Native app and so would expect it to be straight forward  to use on Windows with React Native Windows and on Linux with React Native Skia.

Having a second app that does the same with C# (by porting C# code from BTCPay vault) would offer more choice, show project maturity and potentially be a lot more interesting to enterprises. JavaScript/TypeScript and React Native are great, but they are not necessarily a preferred or first choice for robust enterprise use. 

For one, C# uses compiled code. React Native use a bridge, which is essentially an interpreter.

**Comment by johnheenan** [comment]
I am closing this issue because there is an algorithmic issue with the bolt-nfc-crearor app whose solution is likely to dramatically reduce the incidence of bricked cards.

After proposed fixes, if a user is having problems with a card being set or reset, then as long as a user does not abandon using the app before notification of success, then a card should not become bricked.

Please see [Fault in key change algorithm leading to bricked cards](https://github.com/boltcard/bolt-nfc-android-app/issues/42).

It is possible this issue will need to be reopened if too many users do not properly complete setting or resetting boltcards with the bolt-nfc-creator-app.

**Comment by robertclarkson** [comment]
I think we keep this issue open because the issue still exists In the bolt-nfc-creator app. 

We should as you say deal with the case where the user partially programs the cards by moving them away from the reader too quickly by tracking the state and allowing the programming to continue from the last successful operation.  

Technically this issue belongs on the app repo but this is nearly as good a place to have it

**Comment by johnheenan** [comment]
I have changed the title of this issue **'Multiple approaches to avoid boltcards becoming unusable with a set or reset'** to better reflect where this issue is currently at.

TLDR: 
1) It is lkley the single most effective apprach to avoid boltcards becoming unsuable ('bricked' or 'inconstent state') with a set or reset is to make changes to the bolt-nfc-creator client app. Very specific proposals are in https://github.com/boltcard/bolt-nfc-android-app/issues/42
2) Servers can keep more complete records in their database until a change has been confirmed sucessful
3) Boltcard specifications (or standards) can be more complete. Options can be proposed.

**Comment by johnheenan** [comment]
These comments adds clarification and makes proposals.

**Issues**

There are two issues for those interested in enhancing an existing service with boltcards and so attempting to use existing code.

1) There are no simple source code example of web sites using PHP, Wordpress, Larvel or other SSR Sites (Netlify, Vercel, Node, Cloudfare) with common UI frameworks (React, Lit, Solid, Svelte etc).
2) BTCPay Server is a large project written in C# and is not simple to port from.

**Proposals**

1) Put up some very simple bare examples of such web site types above that use the 'boltcard service' server software, modelled on simple pull payments only.
2) Enhance 'boltcard service' server software to allow use of custodial lightning gateways.

**Background To Proposals With Clarification**

While the 'boltcard service' server software of this repository is a very flexible way to provide a boltcard service as an addition to existing established services, it may not be considered ideal if boltcards do not form a core part of a service. For example, BTCPay Server integrates a 'boltcard service' directly for two main purposes:

1) Link an existing BTCPay Server pull payment to a boltcard
2) Use the bolt-nfc-creator app to both setup boltcards and link to simultaneously created pull payments in BTCPay Server (using the boltcard factory creator plugin).

To use a boltcard it is necessary to have

1) A web site that handles the card request
2) A boltcard service for the web site
3) A payment gateway (custodial or non custodial for lightning funds)

The software of this repository provides 2), hence it is not a standalone turnkey solution, but is a very flexible way to integrate.

BTCPay server combines 1) and 2). Given BTCPay can use multiple custodial lightning gateways (Blink, Breez, Strike) it is as near as it is possible to get to a turnkey solution.

**Comment by johnheenan** [comment]
There is a pull request to fix boltcard bricking documented at https://github.com/boltcard/bolt-nfc-android-app/issues/44.

Since @robertclarkson reopened this issue, I will leave it up to him to decide if he wants to close this issue

**Comment by johnheenan** [comment]
I  have uploaded an Android  side loadable apk to confirm fix for card bricking at https://github.com/johnheenan/bolt-nfc-android-app/releases/tag/v0.3.2. 

Google 'sideload apk' if you wish to try the fix and are not familar with the technique.

From release notes:

> Please see https://github.com/boltcard/bolt-nfc-android-app/issues/44 and https://github.com/boltcard/bolt-nfc-android-app/pull/43
> 
> This release is marked as a pre-release, is not for upload to the Play Store and is for testing verification of fix. You can side-load this release. Uninstall previous official release first.
> 
> Before uninstalling official version, confirm bug by creating a boltcard factory with BTCPay Server, create boltcard, reset boltcard and try to create boltcard again (all with the same physical boltcard). The card will be bricked.
> 
> After installing this pre-release, take a fresh boltcard and go through the same cycle above. The card will not be bricked when created again.
> 
> You can raise issues and create discussions on this forked repository or you can raise issues on the original repository
> 
> **Full Changelog**: https://github.com/johnheenan/bolt-nfc-android-app/compare/v0.3.1...v0.3.2

**Comment by johnheenan** [comment]
Back to square one. The pull request above won't fix bricking: https://github.com/boltcard/bolt-nfc-android-app/issues/44#issuecomment-2316953426

**Comment by johnheenan** [comment]
I put up a new pull request at https://github.com/boltcard/bolt-nfc-android-app/pull/46 with a fix based on using a key version to stop a card being setup if it is already setup (and so bricking). It has been merged and a new Android release, v0.3.2, is in the play store.

I have so far not been able to brick boltcards with the fix in place.

With regard to standards/specifcations, if the fix stays in place as is then there are very minor additions:
A reset will set key 1 version to 0.
A setup will set key 1 version to any value other than 0.

Since @robertclarkson reopened this issue, I will leave it up to him as to when to close this issue.

**Comment by robertclarkson** [comment]
I'll close issue. It does not deal with the edge case of a partially programmed card but it solves the initially reported BTCPayServer issue, where the keys would be reissued for a card that was already programmed
